# This is a basic workflow to help you get started with Actions

name: CI


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: View issue information
        run: |
          python ./main.py
      - name: Commit
        run: |
          git config --global user.name 'Cristi'
          git config --global user.email 'crisemcr@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Add ${{ github.event.issue.title }} word"
          git push
